// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.data;

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200925011345_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Placar")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoMaximaTemporada")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoMinimaTemporada")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeRecordMaximoQuebrado")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeRecordMinimoQuebrado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Placar = 12,
                            PontuacaoMaximaTemporada = 12,
                            PontuacaoMinimaTemporada = 12,
                            QuantidadeRecordMaximoQuebrado = 0,
                            QuantidadeRecordMinimoQuebrado = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
